#!/usr/bin/env python3
"""Generates resume.tex from src/data/resume_data.json.

Usage:
    python scripts/resume-generator/generate_resume.py

After running, compile the PDF with:
    cd resume && xeresume resume.tex
    cp resume/resume.pdf public/resume.pdf
"""

import json
import logging
import re
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).parent.parent.parent
INPUT_FILE = REPO_ROOT / 'resume' / 'resume_data.json'
OUTPUT_FILE = REPO_ROOT / 'resume' / 'resume.tex'

TEX_HEADER = r"""% AUTO-GENERATED by scripts/resume-generator/generate_resume.py -- do not edit manually
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Deedy CV/Resume
% XeLaTeX Template
%
% Original author:
% Debarghya Das (http://www.debarghyadas.com)
%
% License:
% CC BY-NC-SA 3.0 (http://creativecommons.org/licenses/by-nc-sa/3.0/)
%
% Important notes:
% This template needs to be compiled with XeLaTeX.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[letterpaper]{deedy-resume} % Use US Letter paper, change to a4paper for A4

\begin{document}

%----------------------------------------------------------------------------------------
%	TITLE SECTION
%----------------------------------------------------------------------------------------

\lastupdated % Print the Last Updated text at the top right

\namesection{Noah}{Eisen}{
\bigskip
ncteisen@gmail.com | (216) 870 - 2292 % Your contact information
}

%----------------------------------------------------------------------------------------
%	LEFT COLUMN
%----------------------------------------------------------------------------------------

\begin{minipage}[t]{0.29\textwidth} % The left column takes up 33% of the text width of the page

%------------------------------------------------
% Education
%------------------------------------------------
\section{Education}
\subsection{Bachelor of Arts}
\descript{Major, Computer Science}
\descript{Minor, Mathematics}
University of Michigan\\
\location{May 2016\\
Ann Arbor, MI}
\location{ Major GPA: 3.96}
\location{ Cum. GPA: 3.87}

\sectionspace % Some whitespace after the section
%------------------------------------------------
% Links
%------------------------------------------------

\section{Links}
\textbullet{} \href{https://github.com/ncteisen}{ github.com/ncteisen}\\
\textbullet{} \href{https://www.linkedin.com/in/ncteisen}{ linkedin.com/in/ncteisen}\\
\textbullet{} \href{http://noaheisen.com}{ noaheisen.com} \\


\sectionspace % Some whitespace after the section

%------------------------------------------------
% Skills
%------------------------------------------------

\section{Skills}
\subsection{Programming}

\location{Principal Languages}
C++ \textbullet{} C \textbullet{} Python \textbullet{} Kotlin\\
\location{Other Languages}
CSharp \textbullet{} Lua  \textbullet{} SQL \\
Android \textbullet{} Java  \textbullet{} HTML \\
\location{Tools}
Git \textbullet{} \LaTeX \\
\sectionspace % Some whitespace after the section
\sectionspace % Some whitespace after the section
\subsection{Other}
Running \textbullet{} Biking \textbullet{} Climbing \\
Skiing \textbullet{} Juggling \textbullet{} Magic \\
Ceramics \textbullet{}  Creative Writing  \\
Chess \textbullet{} Mountaineering \\

%----------------------------------------------------------------------------------------

\sectionspace % Some whitespace after the section
\sectionspace % Some whitespace after the section

%------------------------------------------------
% Internships
%------------------------------------------------

\section{Internships}
\subsection{Bloomberg L.P.}
\location{May 2015 - Aug 2015}
Full stack internship on the infrastructure team. Built internal tooling to help debug and kill processes running on production machines.

\sectionspace % Some whitespace after the section
\sectionspace % Some whitespace after the section

\subsection{JUMP TRADING LLC}
\location{Jun 2014 - Aug 2014}
QA internship. Wrote Python testing wrappers to validate code that interacts with the exchange. Authored and executed test suites against our live market feed system


\end{minipage} % The end of the left column
\hfill
%
%----------------------------------------------------------------------------------------
%	RIGHT COLUMN
%----------------------------------------------------------------------------------------
%
\begin{minipage}[t]{0.69\textwidth} % The right column takes up 66% of the text width of the page

%------------------------------------------------
% Experience
%------------------------------------------------

\section{Work Experience}

"""

TEX_FOOTER = r"""
\end{minipage} % The end of the right column

%----------------------------------------------------------------------------------------

\end{document}
"""

_LATEX_ESCAPE_MAP = {
    '\\': r'\textbackslash{}',
    '%': r'\%',
    '$': r'\$',
    '&': r'\&',
    '#': r'\#',
    '_': r'\_',
    '^': r'\^{}',
    '{': r'\{',
    '}': r'\}',
    '~': r'\textasciitilde{}',
}
_LATEX_ESCAPE_RE = re.compile(r'[\\%$&#_^{}~]')


def tex_escape(text: str) -> str:
    return _LATEX_ESCAPE_RE.sub(lambda m: _LATEX_ESCAPE_MAP[m.group()], text)


def render_experience(exp: dict, is_first: bool) -> str:
    company = tex_escape(exp['company'])
    title = tex_escape(exp['title'])
    location = tex_escape(exp['location'])
    start = exp['start_date']
    end = exp['end_date']
    description = tex_escape(exp['description'])

    lines = [
        f'\\runsubsection{{{company}}}',
        f'\\descript{{| {title}}}',
        '',
        f'\\location{{{start} \u2013 {end} | {location}}}',
        description,
    ]

    if is_first:
        lines.append('\\vspace{\\topsep} % Hacky fix for awkward extra vertical space')
    lines.append('\\vspace{\\topsep} % Hacky fix for awkward extra vertical space')
    lines.append('\\begin{tightitemize}')

    for item in exp['items']:
        if item.get('skip_pdf', False):
            continue
        lines.append(f'\\item {tex_escape(item["text"])}')

    lines += [
        '\\end{tightitemize}',
        '',
        '\\sectionspace % Some whitespace after the section',
        '',
        '%------------------------------------------------',
        '',
    ]

    return '\n'.join(lines)


def render_tex(data: dict) -> str:
    experiences = [e for e in data['experiences'] if not e.get('skip_pdf', False)]
    blocks = [render_experience(exp, is_first=(i == 0)) for i, exp in enumerate(experiences)]
    return TEX_HEADER + '\n'.join(blocks) + TEX_FOOTER


def main():
    logger.info(f'Reading {INPUT_FILE}')
    with open(INPUT_FILE) as f:
        data = json.load(f)

    tex = render_tex(data)

    logger.info(f'Writing {OUTPUT_FILE}')
    with open(OUTPUT_FILE, 'w') as f:
        f.write(tex)

    logger.info('Done. To compile the PDF:')
    logger.info('  cd resume && xeresume resume.tex')
    logger.info('  cp resume/resume.pdf public/resume.pdf')


if __name__ == '__main__':
    main()
