name: Fetch Social Data

on:
  schedule:
    - cron: '0 10 * * *'  # 3 AM Pacific Time (10 AM UTC)
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }}" > .env
        echo "STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}" >> .env
        echo "STRAVA_REFRESH_TOKEN=${{ secrets.STRAVA_REFRESH_TOKEN }}" >> .env

    - name: Fetch strava activities data
      run: python scripts/strava-activity-fetcher/fetch_activities.py
    
    - name: Run social data fetch script
      run: python scripts/social-scraper/fetch_social_data.py
    
    - name: Clean up .env file
      run: rm .env
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Social Data Fetcher Action"
        git add src/data/social_data.json scripts/strava-activity-fetcher/data/activities.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update social data and Strava activities [skip ci]" && git push) 