var data = ["ACCOUNT", "ACHIEVER", "ACOUSTICS", "ACT", "ACTION", "ACTIVITY", "ACTOR", "ADDITION", "ADJUSTMENT", "ADVERTISEMENT", "ADVICE", "AFTERMATH", "AFTERNOON", "AFTERTHOUGHT", "AGREEMENT", "AIR", "AIRPLANE", "AIRPORT", "ALARM", "AMOUNT", "AMUSEMENT", "ANGER", "ANGLE", "ANIMAL ", "ANSWER", "ANT", "ANTS ", "APPARATUS", "APPAREL", "APPLE", "APPLES ", "APPLIANCE", "APPROVAL", "ARCH", "ARGUMENT", "ARITHMETIC", "ARM", "ARMY", "ART", "ATTACK", "ATTEMPT", "ATTENTION", "ATTRACTION", "AUNT", "AUTHORITY", "BABIES ", "BABY ", "BACK", "BADGE", "BAG", "BAIT", "BALANCE", "BALL", "BALLOON", "BALLS ", "BANANA", "BAND", "BASE", "BASEBALL", "BASIN", "BASKET", "BASKETBALL", "BAT", "BATH", "BATTLE", "BEAD", "BEAM", "BEAN", "BEAR", "BEARS ", "BEAST", "BED", "BEDROOM", "BEDS ", "BEE", "BEEF", "BEETLE", "BEGGAR", "BEGINNER", "BEHAVIOR", "BELIEF", "BELIEVE", "BELL", "BELLS ", "BERRY", "BIKE", "BIKES ", "BIRD", "BIRDS ", "BIRTH", "BIRTHDAY", "BIT", "BITE", "BLADE", "BLOOD", "BLOW", "BOARD", "BOAT", "BOATS ", "BODY", "BOMB", "BONE", "BOOK", "BOOKS ", "BOOT", "BORDER", "BOTTLE", "BOUNDARY", "BOX", "BOY", "BOYS ", "BRAIN", "BRAKE", "BRANCH", "BRASS", "BREAD", "BREAKFAST", "BREATH", "BRICK", "BRIDGE", "BROTHER", "BROTHERS ", "BRUSH", "BUBBLE", "BUCKET", "BUILDING", "BULB", "BUN", "BURN", "BURST", "BUSHES", "BUSINESS", "BUTTER", "BUTTON", "CABBAGE", "CABLE", "CACTUS", "CAKE", "CAKES ", "CALCULATOR", "CALENDAR", "CAMERA", "CAMP", "CAN", "CANNON", "CANVAS", "CAP", "CAPTION", "CAR ", "CARD", "CARE", "CARPENTER", "CARRIAGE", "CARS ", "CART", "CAST", "CAT", "CATS ", "CATTLE", "CAUSE", "CAVE", "CELERY", "CELLAR", "CEMETERY", "CENT", "CHAIN", "CHAIR ", "CHAIRS ", "CHALK", "CHANCE", "CHANGE", "CHANNEL", "CHEESE", "CHERRIES", "CHERRY", "CHESS", "CHICKEN ", "CHICKENS ", "CHILDREN", "CHIN", "CHURCH", "CIRCLE", "CLAM", "CLASS", "CLOCK", "CLOCKS ", "CLOTH", "CLOUD", "CLOUDS ", "CLOVER", "CLUB", "COACH", "COAL", "COAST", "COAT", "COBWEB", "COIL", "COLLAR", "COLOR", "COMB", "COMFORT", "COMMITTEE", "COMPANY", "COMPARISON", "COMPETITION", "CONDITION", "CONNECTION", "CONTROL", "COOK", "COPPER", "COPY", "CORD", "CORK", "CORN ", "COUGH", "COUNTRY", "COVER", "COW", "COWS ", "CRACK", "CRACKER", "CRATE", "CRAYON", "CREAM", "CREATOR", "CREATURE", "CREDIT", "CRIB", "CRIME", "CROOK", "CROW", "CROWD", "CROWN", "CRUSH", "CRY", "CUB", "CUP", "CURRENT", "CURTAIN", "CURVE", "CUSHION", "DAD", "DAUGHTER", "DAY", "DEATH", "DEBT", "DECISION", "DEER", "DEGREE", "DESIGN", "DESIRE", "DESK", "DESTRUCTION", "DETAIL", "DEVELOPMENT", "DIGESTION", "DIME", "DINNER", "DINOSAURS ", "DIRECTION", "DIRT", "DISCOVERY", "DISCUSSION", "DISEASE", "DISGUST", "DISTANCE", "DISTRIBUTION", "DIVISION", "DOCK", "DOCTOR", "DOG", "DOGS ", "DOLL", "DOLLS ", "DONKEY", "DOOR", "DOWNTOWN", "DRAIN", "DRAWER", "DRESS", "DRINK", "DRIVING", "DROP", "DRUG", "DRUM", "DUCK ", "DUCKS ", "DUST", "EAR", "EARTH", "EARTHQUAKE", "EDGE", "EDUCATION", "EFFECT", "EGG", "EGGNOG", "EGGS ", "ELBOW", "END", "ENGINE", "ERROR", "EVENT", "EXAMPLE", "EXCHANGE", "EXISTENCE", "EXPANSION", "EXPERIENCE", "EXPERT", "EYE", "EYES", "FACE", "FACT", "FAIRIES ", "FALL", "FAMILY", "FAN", "FANG ", "FARM", "FARMER ", "FATHER", "FATHER", "FAUCET", "FEAR", "FEAST", "FEATHER", "FEELING", "FEET", "FICTION", "FIELD", "FIFTH", "FIGHT", "FINGER", "FINGER", "FIRE ", "FIREMAN", "FISH", "FLAG", "FLAME", "FLAVOR", "FLESH", "FLIGHT", "FLOCK", "FLOOR", "FLOWER", "FLOWERS ", "FLY", "FOG", "FOLD", "FOOD", "FOOT", "FORCE", "FORK", "FORM", "FOWL", "FRAME", "FRICTION", "FRIEND", "FRIENDS ", "FROG", "FROGS ", "FRONT", "FRUIT", "FUEL", "FURNITURE", "ALLEY", "GAME", "GARDEN", "GATE", "GEESE", "GHOST", "GIANTS ", "GIRAFFE", "GIRL", "GIRLS ", "GLASS", "GLOVE", "GLUE", "GOAT", "GOLD", "GOLDFISH", "GOOD-BYE ", "GOOSE", "GOVERNMENT", "GOVERNOR", "GRADE", "GRAIN", "GRANDFATHER", "GRANDMOTHER", "GRAPE", "GRASS", "GRIP", "GROUND", "GROUP", "GROWTH", "GUIDE", "GUITAR", "GUN", "HAIR", "HAIRCUT", "HALL", "HAMMER", "HAND", "HANDS ", "HARBOR", "HARMONY", "HAT", "HATE", "HEAD", "HEALTH", "HEARING", "HEART", "HEAT", "HELP", "HEN", "HILL ", "HISTORY", "HOBBIES", "HOLE", "HOLIDAY", "HOME ", "HONEY", "HOOK", "HOPE", "HORN", "HORSE", "HORSES ", "HOSE", "HOSPITAL", "HOT", "HOUR", "HOUSE", "HOUSES ", "HUMOR", "HYDRANT", "ICE", "ICICLE", "IDEA", "IMPULSE", "INCOME", "INCREASE", "INDUSTRY", "INK", "INSECT", "INSTRUMENT", "INSURANCE", "INTEREST", "INVENTION", "IRON", "ISLAND", "JAIL", "JAM", "JAR", "JEANS", "JELLY", "JELLYFISH", "JEWEL", "JOIN", "JOKE", "JOURNEY", "JUDGE", "JUICE", "JUMP", "KETTLE", "KEY", "KICK", "KISS", "KITE", "KITTEN", "KITTENS ", "KITTY ", "KNEE", "KNIFE", "KNOT", "KNOWLEDGE", "LABORER", "LACE", "LADYBUG", "LAKE", "LAMP", "LAND", "LANGUAGE", "LAUGH", "LAWYER", "LEAD", "LEAF", "LEARNING", "LEATHER", "LEG ", "LEGS", "LETTER", "LETTERS ", "LETTUCE", "LEVEL", "LIBRARY", "LIFT", "LIGHT", "LIMIT", "LINE", "LINEN", "LIP", "LIQUID", "LIST", "LIZARDS ", "LOAF", "LOCK", "LOCKET", "LOOK", "LOSS", "LOVE", "LOW", "LUMBER", "LUNCH", "LUNCHROOM", "MACHINE", "MAGIC", "MAID", "MAILBOX", "MAN", "MANAGER", "MAP", "MARBLE", "MARK", "MARKET", "MASK", "MASS", "MATCH", "MEAL", "MEASURE", "MEAT", "MEETING", "MEMORY", "MEN", "METAL", "MICE ", "MIDDLE", "MILK", "MIND", "MINE", "MINISTER", "MINT", "MINUTE", "MIST", "MITTEN", "MOM", "MONEY", "MONKEY", "MONTH", "MOON", "MORNING", "MOTHER", "MOTION", "MOUNTAIN", "MOUTH", "MOVE", "MUSCLE", "MUSIC", "NAIL", "NAME", "NATION", "NECK", "NEED", "NEEDLE", "NERVE", "NEST ", "NET", "NEWS", "NIGHT", "NOISE", "NORTH", "NOSE", "NOTE", "NOTEBOOK", "NUMBER", "NUT", "OATMEAL", "OBSERVATION", "OCEAN", "OFFER", "OFFICE", "OIL", "OPERATION", "OPINION", "ORANGE", "ORANGES ", "ORDER", "ORGANIZATION", "ORNAMENT", "OVEN", "OWL", "OWNER", "PAGE", "PAIL", "PAIN", "PAINT", "PAN", "PANCAKE", "PAPER", "PARCEL", "PARENT", "PARK", "PART", "PARTNER", "PARTY", "PASSENGER", "PASTE", "PATCH", "PAYMENT", "PEACE", "PEAR", "PEN", "PENCIL", "PERSON", "PEST", "PET", "PETS ", "PICKLE", "PICTURE", "PIE", "PIES ", "PIG", "PIGS ", "PIN", "PIPE", "PIZZAS ", "PLACE", "PLANE", "PLANES ", "PLANT", "PLANTATION", "PLANTS ", "PLASTIC", "PLATE", "PLAY", "PLAYGROUND", "PLEASURE", "PLOT", "PLOUGH", "POCKET", "POINT", "POISON", "POLICE", "POLISH", "POLLUTION", "POPCORN", "PORTER", "POSITION", "POT", "POTATO", "POWDER", "POWER", "PRICE", "PRINT", "PRISON", "PROCESS", "PRODUCE", "PROFIT", "PROPERTY", "PROSE", "PROTEST", "PULL", "PUMP", "PUNISHMENT", "PURPOSE", "PUSH", "QUARTER", "QUARTZ", "QUEEN", "QUESTION", "QUICKSAND", "QUIET", "QUILL", "QUILT", "QUINCE", "QUIVER", "RABBIT ", "RABBITS ", "RAIL", "RAILWAY", "RAIN", "RAINSTORM", "RAKE", "RANGE", "RAT", "RATE", "RAY", "REACTION", "READING", "REASON", "RECEIPT", "RECESS", "RECORD", "REGRET", "RELATION", "RELIGION", "REPRESENTATIVE", "REQUEST", "RESPECT", "REST", "REWARD", "RHYTHM", "RICE", "RIDDLE", "RIFLE", "RING", "RINGS ", "RIVER", "ROAD", "ROBIN ", "ROCK", "ROD", "ROLL", "ROOF", "ROOM", "ROOT", "ROSE", "ROUTE", "RUB", "RULE", "RUN", "SACK", "SAIL", "SALT", "SAND", "SCALE", "SCARECROW", "SCARF", "SCENE", "SCENT", "SCHOOL", "SCIENCE", "SCISSORS", "SCREW", "SEA", "SEASHORE", "SEAT", "SECRETARY", "SEED", "SELECTION", "SELF", "SENSE", "SERVANT", "SHADE", "SHAKE", "SHAME", "SHAPE", "SHEEP", "SHEET", "SHELF", "SHIP", "SHIRT", "SHOCK", "SHOE", "SHOES ", "SHOP", "SHOW", "SIDE", "SIDEWALK", "SIGN", "SILK", "SILVER", "SINK", "SISTER", "SISTERS ", "SIZE", "SKATE", "SKIN", "SKIRT", "SKY", "SLAVE", "SLEEP", "SLEET", "SLIP", "SLOPE", "SMASH", "SMELL", "SMILE", "SMOKE", "SNAIL", "SNAILS ", "SNAKE", "SNAKES ", "SNEEZE", "SNOW", "SOAP", "SOCIETY", "SOCK", "SODA", "SOFA", "SON", "SONG", "SONGS ", "SORT", "SOUND", "SOUP", "SPACE", "SPADE", "SPARK", "SPIDERS ", "SPONGE", "SPOON", "SPOT", "SPRING", "SPY", "SQUARE", "SQUIRREL", "STAGE", "STAMP", "STAR", "START", "STATEMENT", "STATION", "STEAM", "STEEL", "STEM", "STEP", "STEW", "STICK", "STICKS ", "STITCH", "STOCKING", "STOMACH", "STONE", "STOP", "STORE", "STORY", "STOVE", "STRANGER", "STRAW", "STREAM", "STREET", "STRETCH", "STRING", "STRUCTURE", "SUBSTANCE", "SUGAR", "SUGGESTION", "SUIT", "SUMMER", "SUN", "SUPPORT", "SURPRISE", "SWEATER", "SWIM", "SWING", "SYSTEM", "TABLE", "TAIL", "TALK", "TANK", "TASTE", "TAX", "TEACHING", "TEAM", "TEETH ", "TEMPER", "TENDENCY", "TENT", "TERRITORY", "TEST", "TEXTURE", "THEORY", "THING", "THINGS ", "THOUGHT", "THREAD", "THRILL", "THROAT", "THRONE", "THUMB", "THUNDER", "TICKET", "TIGER", "TIME", "TIN", "TITLE", "TOAD", "TOE", "TOES", "TOMATOES ", "TONGUE", "TOOTH", "TOOTHBRUSH", "TOOTHPASTE", "TOP ", "TOUCH", "TOWN", "TOY ", "TOYS ", "TRADE", "TRAIL", "TRAIN", "TRAINS ", "TRAMP", "TRANSPORT", "TRAY", "TREATMENT", "TREE", "TREES ", "TRICK", "TRIP", "TROUBLE", "TROUSERS", "TRUCK", "TRUCKS ", "TUB", "TURKEY", "TURN", "TWIG", "TWIST", "UMBRELLA", "UNCLE", "UNDERWEAR", "UNIT", "USE", "VACATION", "VALUE", "VAN", "VASE", "VEGETABLE", "VEIL", "VEIN", "VERSE", "VESSEL", "VEST", "VIEW", "VISITOR", "VOICE", "VOLCANO", "VOLLEYBALL", "VOYAGE", "WALK", "WALL", "WAR", "WASH", "WASTE", "WATCH", "WATER", "WAVE", "WAVES ", "WAX", "WAY", "WEALTH", "WEATHER", "WEEK", "WEIGHT", "WHEEL", "WHIP", "WHISTLE", "WILDERNESS", "WIND ", "WINDOW ", "WINE", "WING", "WINTER", "WIRE", "WISH", "WOMAN", "WOMEN", "WOOD", "WOOL", "WORD", "WORK", "WORM", "WOUND", "WREN", "WRENCH", "WRIST", "WRITER", "WRITING", "YAK", "YAM", "YARD", "YARN", "YEAR", "YOKE", "ZEBRA ", "ZEPHYR", "ZINC", "ZIPPER", "ZOO"];
var movieData = ["The Shawshank Redemption",
	"The Godfather",
	"The Godfather, Part II",
	"The Dark Knight",
	"Pulp Fiction",
	"The Good, The Bad and The Ugly",
	"12 Angry Men",
	"Schindler's List",
	"The Lord of the Rings: The Return of the King",
	"Fight Club",
	"The Fellowship Of The Ring",
	"Star Wars: Episode V - The Empire Strikes Back",
	"Inception",
	"Forrest Gump",
	"One Flew Over the Cuckoo's Nest",
	"The Lord of the Rings: The Two Towers",
	"Interstellar",
	"Goodfellas",
	"The Matrix",
	"Star Wars: Episode IV - A New Hope",
	"Seven Samurai",
	"City of God",
	"Se7en",
	"The Usual Suspects",
	"The Silence of the Lambs",
	"It's a Wonderful Life",
	"Once Upon a Time in the West",
	"Leon: The Professional",
	"Life Is Beautiful",
	"Casablanca",
	"Raiders of the Lost Ark",
	"American History X",
	"Saving Private Ryan",
	"City Lights",
	"Psycho",
	"Spirited Away",
	"Rear Window",
	"Intouchables",
	"Modern Times",
	"Whiplash",
	"Terminator 2: Judgment Day",
	"Memento",
	"The Green Mile",
	"The Pianist",
	"The Departed",
	"Sunset Boulevard",
	"Apocalypse Now",
	"Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb",
	"Gladiator",
	"Back to the Future",
	"Alien",
	"The Prestige",
	"The Great Dictator",
	"The Lives of Others",
	"The Lion King",
	"Django Unchained",
	"The Dark Knight Rises",
	"Cinema Paradiso",
	"The Shining",
	"Paths of Glory",
	"American Beauty",
	"Wall-E",
	"North by Northwest",
	"Aliens",
	"Citizen Kane",
	"Vertigo",
	"Amelie",
	"M",
	"Das Boot",
	"Grave of the Fireflies",
	"Toy Story 3",
	"Oldboy",
	"Princess Mononoke",
	"Star Wars: Episode VI - Return of the Jedi",
	"Once Upon a Time in America",
	"A Clockwork Orange",
	"Reservoir Dogs",
	"Taxi Driver",
	"Double Indemnity",
	"Braveheart",
	"Requiem for a Dream",
	"To Kill a Mockingbird",
	"Lawrence of Arabia",
	"Witness for the Prosecution",
	"Eternal Sunshine of the Spotless Mind",
	"Full Metal Jacket",
	"Singin' in the Rain",
	"The Sting",
	"Bicycle Thieves",
	"Amadeus",
	"Monty Python and the Holy Grail",
	"Snatch",
	"Rashomon",
	"L.A. Confidential",
	"For a Few Dollars More",
	"2001: A Space Odyssey",
	"The Kid",
	"All About Eve",
	"The Apartment",
	"Some Like It Hot",
	"Inglourious Basterds",
	"Birdman",
	"Indiana Jones and the Last Crusade",
	"The Treasure of the Sierra Madre",
	"The Third Man",
	"A Seperation",
	"Yojimbo",
	"Toy Story",
	"Batman Begins",
	"Metropolis",
	"Like Stars on Earth",
	"Unforgiven",
	"Scarface",
	"Raging Bull",
	"Up",
	"Chinatown",
	"3 Idiots",
	"The Great Escape",
	"Downfall",
	"Boyhood",
	"Die Hard",
	"On the Waterfront",
	"Pan's Labyrinth",
	"Mr. Smith Goes to Washington",
	"The Hunt",
	"Heat",
	"CM101MMXI Fundamentals",
	"Gone Girl",
	"The Bridge on the River Kwai",
	"Good Will Hunting",
	"The Bandit",
	"My Neighbor Totoro",
	"The Seventh Seal",
	"Ikiru",
	"The Gold Rush",
	"The Elephant Man",
	"The Wolf of Wall Street",
	"Ran",
	"Wild Strawberries",
	"Blade Runner",
	"The General",
	"Lock, Stock and Two Smoking Barrels",
	"The Secret in Their Eyes",
	"Casino",
	"Gran Torino",
	"The Big Lebowski",
	"Warrior",
	"Rebecca",
	"V for Vendetta",
	"Howl's Moving Castle",
	"Paint It Yellow",
	"The Deer Hunter",
	"It Happened One Night",
	"Cool Hand Luke",
	"How to Train Your Dragon",
	"Fargo",
	"Judgment at Nuremberg",
	"Trainspotting",
	"Gone with the Wind",
	"Rush",
	"Into the Wild",
	"The Maltese Falcon",
	"A Beautiful Mind",
	"Dial M for Murder",
	"The Sixth Sense",
	"The Wages of Fear",
	"Hotel Rwanda",
	"The Thing",
	"Finding Nemo",
	"Mary and Max",
	"No Country for Old Men",
	"Butch Cassidy and the Sundance Kid",
	"Kill Bill: Vol. 1",
	"Platoon",
	"Life of Brian",
	"Incendies",
	"Guardians of the Galaxy",
	"Dil Chahta Hai",
	"12 Years a Slave",
	"Network",
	"Touch of Evil",
	"Diabolique (1955)",
	"Annie Hall",
	"The Princess Bride",
	"There Will Be Blood",
	"The Grand Budapest Hotel",
	"Stand by Me",
	"Sin City",
	"Ben-Hur",
	"The 400 Blows",
	"Amores Perros",
	"In the Name of the Father",
	"Million Dollar Baby",
	"The Grapes of Wrath",
	"The Wizard of Oz",
	"Hachi: A Dog's Tale",
	"Persona",
	"The Best Years of Our Lives",
	"The Avengers",
	"Nausicaä of the Valley of the Wind",
	"The Bourne Ultimatum",
	"Gandhi",
	"The Imitation Game",
	"Donnie Darko",
	"8 1/2",
	"Gangs of Wasseypur",
	"Strangers on a Train",
	"Infernal Affairs",
	"Stalker",
	"12 Monkeys",
	"Jaws",
	"Shutter Island",
	"X-Men: Days of Future Past",
	"High Noon",
	"Lagaan: Once Upon a Time in India",
	"Notorious",
	"The Terminator",
	"Before Sunrise",
	"The King's Speech",
	"Groundhog Day",
	"Harry Potter and the Deathly Hallows: Part 2",
	"Fanny and Alexander",
	"Ip Man",
	"The Battle of Algiers",
	"Rocky",
	"Dog Day Afternoon",
	"The Night of the Hunter",
	"Monsters, Inc.",
	"La Haine",
	"Memories of Murder",
	"La Strada",
	"Pirates of the Caribbean: The Curse of the Black Pearl",
	"Who's Afraid of Virginia Woolf?",
	"Barry Lyndon",
	"A Fistful of Dollars",
	"Castle in the Sky",
	"The Truman Show",
	"The Big Sleep",
	"The Help",
	"Jurassic Park",
	"Roman Holiday",
	"The Graduate",
	"The Hustler",
	"Papillon",
	"Beauty and the Beast",
	"In the Mood for Love",
	"The Celebration",
	"Prisoners",
	"Rope",
	"Swades: We, the People"
];

var defaultData = ["AFRICA",
	"AGENT",
	"AIR",
	"ALIEN",
	"ALPS",
	"AMAZON",
	"AMBULANCE",
	"AMERICA",
	"ANGEL",
	"ANTARCTICA",
	"APPLE",
	"ARM",
	"ATLANTIS",
	"AUSTRALIA",
	"AZTEC",
	"BACK",
	"BALL",
	"BAND",
	"BANK",
	"BAR",
	"BARK",
	"BAT",
	"BATTERY",
	"BEACH",
	"BEAR",
	"BEAT",
	"BED",
	"BEIJING",
	"BELL",
	"BELT",
	"BERLIN",
	"BERMUDA",
	"BERRY",
	"BILL",
	"BLOCK",
	"BOARD",
	"BOLT",
	"BOMB",
	"BOND",
	"BOOM",
	"BOOT",
	"BOTTLE",
	"BOW",
	"BOX",
	"BRIDGE",
	"BRUSH",
	"BUCK",
	"BUFFALO",
	"BUG",
	"BUGLE",
	"BUTTON",
	"CALF",
	"CANADA",
	"CAP",
	"CAPITAL",
	"CAR",
	"CARD",
	"CARROT",
	"CASINO",
	"CAST",
	"CAT",
	"CELL",
	"CENTAUR",
	"CENTER",
	"CHAIR",
	"CHANGE",
	"CHARGE",
	"CHECK",
	"CHEST",
	"CHICK",
	"CHINA",
	"CHOCOLATE",
	"CHURCH",
	"CIRCLE",
	"CLIFF",
	"CLOAK",
	"CLUB",
	"CODE",
	"COLD",
	"COMIC",
	"COMPOUND",
	"CONCERT",
	"CONDUCTOR",
	"CONTRACT",
	"COOK",
	"COPPER",
	"COTTON",
	"COURT",
	"COVER",
	"CRANE",
	"CRASH",
	"CRICKET",
	"CROSS",
	"CROWN",
	"CYCLE",
	"CZECH",
	"DANCE",
	"DATE",
	"DAY",
	"DEATH",
	"DECK",
	"DEGREE",
	"DIAMOND",
	"DICE",
	"DINOSAUR",
	"DISEASE",
	"DOCTOR",
	"DOG",
	"DRAFT",
	"DRAGON",
	"DRESS",
	"DRILL",
	"DROP",
	"DUCK",
	"DWARF",
	"EAGLE",
	"EGYPT",
	"EMBASSY",
	"ENGINE",
	"ENGLAND",
	"EUROPE",
	"EYE",
	"FACE",
	"FAIR",
	"FALL",
	"FAN",
	"FENCE",
	"FIELD",
	"FIGHTER",
	"FIGURE",
	"FILE",
	"FILM",
	"FIRE",
	"FISH",
	"FLUTE",
	"FLY",
	"FOOT",
	"FORCE",
	"FOREST",
	"FORK",
	"FRANCE",
	"GAME",
	"GAS",
	"GENIUS",
	"GERMANY",
	"GHOST",
	"GIANT",
	"GLASS",
	"GLOVE",
	"GOLD",
	"GRACE",
	"GRASS",
	"GREECE",
	"GREEN",
	"GROUND",
	"HAM",
	"HAND",
	"HAWK",
	"HEAD",
	"HEART",
	"HELICOPTER",
	"HIMALAYAS",
	"HOLE",
	"HOLLYWOOD",
	"HONEY",
	"HOOD",
	"HOOK",
	"HORN",
	"HORSE",
	"HORSESHOE",
	"HOSPITAL",
	"HOTEL",
	"ICE",
	"ICE CREAM",
	"INDIA",
	"IRON",
	"IVORY",
	"JACK",
	"JAM",
	"JET",
	"JUPITER",
	"KANGAROO",
	"KETCHUP",
	"KEY",
	"KID",
	"KING",
	"KIWI",
	"KNIFE",
	"KNIGHT",
	"LAB",
	"LAP",
	"LASER",
	"LAWYER",
	"LEAD",
	"LEMON",
	"LEPRECHAUN",
	"LIFE",
	"LIGHT",
	"LIMOUSINE",
	"LINE",
	"LINK",
	"LION",
	"LITTER",
	"LOCH NESS",
	"LOCK",
	"LOG",
	"LONDON",
	"LUCK",
	"MAIL",
	"MAMMOTH",
	"MAPLE",
	"MARBLE",
	"MARCH",
	"MASS",
	"MATCH",
	"MERCURY",
	"MEXICO",
	"MICROSCOPE",
	"MILLIONAIRE",
	"MINE",
	"MINT",
	"MISSILE",
	"MODEL",
	"MOLE",
	"MOON",
	"MOSCOW",
	"MOUNT",
	"MOUSE",
	"MOUTH",
	"MUG",
	"NAIL",
	"NEEDLE",
	"NET",
	"NEW YORK",
	"NIGHT",
	"NINJA",
	"NOTE",
	"NOVEL",
	"NURSE",
	"NUT",
	"OCTOPUS",
	"OIL",
	"OLIVE",
	"OLYMPUS",
	"OPERA",
	"ORANGE",
	"ORGAN",
	"PALM",
	"PAN",
	"PANTS",
	"PAPER",
	"PARACHUTE",
	"PARK",
	"PART",
	"PASS",
	"PASTE",
	"PENGUIN",
	"PHOENIX",
	"PIANO",
	"PIE",
	"PILOT",
	"PIN",
	"PIPE",
	"PIRATE",
	"PISTOL",
	"PIT",
	"PITCH",
	"PLANE",
	"PLASTIC",
	"PLATE",
	"PLATYPUS",
	"PLAY",
	"PLOT",
	"POINT",
	"POISON",
	"POLE",
	"POLICE",
	"POOL",
	"PORT",
	"POST",
	"POUND",
	"PRESS",
	"PRINCESS",
	"PUMPKIN",
	"PUPIL",
	"PYRAMID",
	"QUEEN",
	"RABBIT",
	"RACKET",
	"RAY",
	"REVOLUTION",
	"RING",
	"ROBIN",
	"ROBOT",
	"ROCK",
	"ROME",
	"ROOT",
	"ROSE",
	"ROULETTE",
	"ROUND",
	"ROW",
	"RULER",
	"SATELLITE",
	"SATURN",
	"SCALE",
	"SCHOOL",
	"SCIENTIST",
	"SCORPION",
	"SCREEN",
	"SCUBA DIVER",
	"SEAL",
	"SERVER",
	"SHADOW",
	"SHAKESPEARE",
	"SHARK",
	"SHIP",
	"SHOE",
	"SHOP",
	"SHOT",
	"SINK",
	"SKYSCRAPER",
	"SLIP",
	"SLUG",
	"SMUGGLER",
	"SNOW",
	"SNOWMAN",
	"SOCK",
	"SOLDIER",
	"SOUL",
	"SOUND",
	"SPACE",
	"SPELL",
	"SPIDER",
	"SPIKE",
	"SPINE",
	"SPOT",
	"SPRING",
	"SPY",
	"SQUARE",
	"STADIUM",
	"STAFF",
	"STAR",
	"STATE",
	"STICK",
	"STOCK",
	"STRAW",
	"STREAM",
	"STRIKE",
	"STRING",
	"SUB",
	"SUIT",
	"SUPERHERO",
	"SWING",
	"SWITCH",
	"TABLE",
	"TABLET",
	"TAG",
	"TAIL",
	"TAP",
	"TEACHER",
	"TELESCOPE",
	"TEMPLE",
	"THEATER",
	"THIEF",
	"THUMB",
	"TICK",
	"TIE",
	"TIME",
	"TOKYO",
	"TOOTH",
	"TORCH",
	"TOWER",
	"TRACK",
	"TRAIN",
	"TRIANGLE",
	"TRIP",
	"TRUNK",
	"TUBE",
	"TURKEY",
	"UNDERTAKER",
	"UNICORN",
	"VACUUM",
	"VAN",
	"VET",
	"WAKE",
	"WALL",
	"WAR",
	"WASHER",
	"WASHINGTON",
	"WATCH",
	"WATER",
	"WAVE",
	"WEB",
	"WELL",
	"WHALE",
	"WHIP",
	"WIND",
	"WITCH",
	"WORM",
	"YARD"
];

var dirty = [
	"2 GIRLS 1 CUP",
	"ALABAMA HOT POCKET",
	"ALASKAN PIPELINE",
	"ANAL",
	"ANILINGUS",
	"ANUS",
	"APESHIT",
	"ARSEHOLE",
	"ASS",
	"ASSHOLE",
	"ASSMUNCH",
	"AUTO EROTIC",
	"AUTOEROTIC",
	"BABELAND",
	"BABY JUICE",
	"BALL GAG",
	"BALL GRAVY",
	"BALL KICKING",
	"BALL LICKING",
	"BALL SACK",
	"BALL SUCKING",
	"BANGBROS",
	"BAREBACK",
	"BARELY LEGAL",
	"BARENAKED",
	"BASTARD",
	"BASTARDO",
	"BASTINADO",
	"BBW",
	"BDSM",
	"BEAVER CLEAVER",
	"BEAVER LIPS",
	"BESTIALITY",
	"BIG BLACK",
	"BIG BREASTS",
	"BIG KNOCKERS",
	"BIG TITS",
	"BIMBOS",
	"BIRDLOCK",
	"BITCH",
	"BITCHES",
	"BLACK COCK",
	"BLONDE ACTION",
	"BLONDE ON BLONDE ACTION",
	"BLOWJOB",
	"BLOW YOUR LOAD",
	"BLUE WAFFLE",
	"BLUMPKIN",
	"BOLLOCKS",
	"BONDAGE",
	"BONER",
	"BOOB",
	"BOOTY CALL",
	"BROWN SHOWERS",
	"BRUNETTE ACTION",
	"BUKKAKE",
	"BULLDYKE",
	"BULLET VIBE",
	"BULLSHIT",
	"BUNG HOLE",
	"BUNGHOLE",
	"BUSTY",
	"BUTT",
	"BUTTCHEEKS",
	"BUTTHOLE",
	"CAMEL TOE",
	"CAMGIRL",
	"CAMSLUT",
	"CAMWHORE",
	"CARPET MUNCHER",
	"CHOCOLATE ROSEBUDS",
	"CIRCLEJERK",
	"CLEVELAND STEAMER",
	"CLIT",
	"CLITORIS",
	"CLOVER CLAMPS",
	"CLUSTERFUCK",
	"COCKS",
	"CORNHOLE",
	"CREAMPIE",
	"CUM",
	"CUMMING",
	"CUNNILINGUS",
	"CUNT",
	"DEEP THROAT",
	"DICK",
	"DILDO",
	"DINGLEBERRY",
	"DIRTY PILLOWS",
	"DIRTY SANCHEZ",
	"DOGGIE STYLE",
	"DOMINATION",
	"DOMINATRIX",
	"DONKEY PUNCH",
	"DOUBLE DONG",
	"DOUBLE PENETRATION",
	"DP ACTION",
	"DRY HUMP",
	"EAT MY ASS",
	"EJACULATION",
	"EROTIC",
	"EROTISM",
	"ESCORT",
	"EUNUCH",
	"FAGGOT",
	"FECAL",
	"FELLATIO",
	"FEMALE SQUIRTING",
	"FINGERBANG",
	"FINGERING",
	"FISTING",
	"FOOT FETISH",
	"FOOTJOB",
	"FUCK",
	"FUCK BUTTONS",
	"FUCKTARDS",
	"FUDGE PACKER",
	"GANG BANG",
	"GAY SEX",
	"GENITALS",
	"GIANT COCK",
	"GIRL ON TOP",
	"GIRLS GONE WILD",
	"GOLDEN SHOWER",
	"GROUP SEX",
	"G-SPOT",
	"HAND JOB",
	"HARDCORE",
	"HENTAI",
	"HOMOEROTIC",
	"HOOKER",
	"HOT CHICK",
	"HUMPING",
	"INCEST",
	"INTERCOURSE",
	"JACK OFF",
	"JAILBAIT",
	"JELLY DONUT",
	"JERK OFF",
	"JIZZ",
	"JUGGS",
	"KINKY",
	"LEATHER RESTRAINT",
	"LEMON PARTY",
	"LOLITA",
	"LOVEMAKING",
	"MALE SQUIRTING",
	"MASTURBATE",
	"MENAGE A TROIS",
	"MILF",
	"MISSIONARY POSITION",
	"MOTHERFUCKER",
	"MOUND OF VENUS",
	"MUFFDIVING",
	"NIMPHOMANIA",
	"NIPPLE",
	"NSFW IMAGES",
	"NUDE",
	"NYMPHO",
	"OCTOPUSSY",
	"ORGASM",
	"ORGY",
	"PAEDOPHILE",
	"PANTY",
	"PEDOBEAR",
	"PEGGING",
	"PENIS",
	"PHONE SEX",
	"PLAYBOY",
	"PLEASURE CHEST",
	"PONYPLAY",
	"POON",
	"POONTANG",
	"POOPCHUTE",
	"PORN",
	"PRINCE ALBERT PIERCING",
	"PUBES",
	"PUSSY",
	"QUEEF",
	"RAGING BONER",
	"RECTUM",
	"REVERSE COWGIRL",
	"RIMJOB",
	"RIMMING",
	"RUSTY TROMBONE",
	"SADISM",
	"SCAT",
	"SCHLONG",
	"SCISSORING",
	"SEMEN",
	"SEX",
	"SHAVED BEAVER",
	"SHAVED PUSSY",
	"SKEET",
	"SLUT",
	"S&M",
	"SMUT",
	"SNATCH",
	"SODOMY",
	"SPLOOGE",
	"STRAP ON",
	"STRIP CLUB",
	"SULTRY WOMEN",
	"TEA BAGGING",
	"THREESOME",
	"TITTY",
	"TOPLESS",
	"TRANNY",
	"TUSHY",
	"TWAT",
	"TWO GIRLS ONE CUP",
	"URETHRA PLAY",
	"VAGINA",
	"VENUS MOUND",
	"VIBRATOR",
	"VULVA",
	"WANK",
	"WET DREAM",
	"WRINKLED STARFISH",
	"YELLOW SHOWERS",
	"ZOOPHILIA",
]


